---
ingress_worker_ports:
  # - 80/tcp
  # - 443/tcp
  # - 443/udp

consul_client_to_server_ports:
  # - 4646/tcp
  # - 4647/tcp

consul_server_admin_ports:
  - 8500/tcp

consul_server_to_server_ports:
  # - 4647/tcp
  # - 4648/tcp
  # - 4648/udp
...
