---
- ansible.builtin.file:
    group: "{{ 'nomad' if 'manager' in group_names else 'root' }}"
    mode: '0750'
    owner: "{{ 'nomad' if 'manager' in group_names else 'root' }}"
    path: /etc/nomad.d/certs
    state: directory
  name: Setup Nomad certificates folder permissions

- ansible.builtin.stat:
    path: "/etc/nomad.d/certs/{{ certificate.domain_name }}-agent-ca.pem"
  delegate_to: "{{ first_manager }}"
  name: Check for CA certificate
  register: ca_certificate

- ansible.builtin.stat:
    path: "/etc/nomad.d/certs/{{ certificate.domain_name }}-agent-ca-key.pem"
  delegate_to: "{{ first_manager }}"
  name: Check for CA private key
  register: ca_private_key

- ansible.builtin.command:
    cmd: >
      nomad tls ca create
        -common-name "{{ certificate.common_name }}"
        -country "{{ certificate.country }}"
        -days {{ certificate.days }}
        -domain {{ certificate.domain_name }}
        -locality "{{ certificate.locality }}"
        -name-constraint
        -organization "{{ certificate.organization }}"
        -organizational-unit "{{ certificate.organizational_unit }}"
        -postal-code "{{ certificate.postal_code }}"
        -province "{{ certificate.province }}"
        -street-address "{{ certificate.street_address }}"
  args:
    chdir: /etc/nomad.d/certs
  delegate_to: "{{ first_manager }}"
  name: Generate Nomad CA's private key and certificate
  when:
    - not ca_certificate.stat.exists
    - not ca_private_key.stat.exists

- ansible.builtin.fetch:
    dest: "{{ playbook_dir }}/../.cache/"
    flat: true
    src: "/etc/nomad.d/certs/{{ certificate.domain_name }}-agent-ca.pem"
  delegate_to: "{{ first_manager }}"
  name: Copy Nomad CA's certificate to cache

- ansible.builtin.fetch:
    dest: "{{ playbook_dir }}/../.cache/"
    flat: true
    src: "/etc/nomad.d/certs/{{ certificate.domain_name }}-agent-ca-key.pem"
  delegate_to: "{{ first_manager }}"
  name: Copy Nomad CA's private key to cache

- ansible.builtin.copy:
    dest: /etc/nomad.d/certs/
    group: "{{ 'nomad' if 'manager' in group_names else 'root' }}"
    mode: '0750'
    owner: "{{ 'nomad' if 'manager' in group_names else 'root' }}"
    src: "{{ playbook_dir }}/../.cache/{{ certificate.domain_name }}-agent-ca.pem"
  name: Copy Nomad CA's certificate from cache

- ansible.builtin.copy:
    dest: /etc/nomad.d/certs/
    group: "{{ 'nomad' if 'manager' in group_names else 'root' }}"
    mode: '0750'
    owner: "{{ 'nomad' if 'manager' in group_names else 'root' }}"
    src: "{{ playbook_dir }}/../.cache/{{ certificate.domain_name }}-agent-ca-key.pem"
  name: Copy Nomad CA's private key from cache
  when: "'manager' in group_names"
...
