---
  - ansible.builtin.stat:
      path: "{{ paths.certificate }}"
    name: Get certificate file properties
    register: certificate_file
    when: not force_remove

  - community.crypto.x509_certificate_info:
      path: "{{ paths.certificate }}"
      valid_at:
        month: +1m
    name: Get certificate data
    register: certificate_data
    when:
      - not force_remove
      - certificate_file.stat.exists

  - ansible.builtin.file:
      path: "{{ paths.certificate }}"
      state: absent
    name: Remove certificate if expires soon or forced removal
    when: >
      certificate_data.skipped
      or not certificate_data.valid_at.month

  - ansible.builtin.file:
      path: "{{ paths.private_key }}"
      state: absent
    name: Remove private key if certificate expires soon or forced removal
    when: >
      certificate_data.skipped
      or not certificate_data.valid_at.month
...
