---
- ansible.builtin.set_fact:
    worker_ips: >-
      {{
        ansible_play_hosts
        | reject('in', groups['manager'])
        | map('extract', hostvars, 'ansible_default_ipv4')
        | map(attribute='address')
        | reject('equalto', ansible_default_ipv4.address)
        | list
      }}
  name: Collect other worker IPs

- community.general.ufw:
    from_ip: "{{ ip }}"
    log: true
    proto: "{{ proto }}"
    rule: allow
    to_port: "{{ port_no }}"
  loop: "{{ query('nested', worker_ips, nomad_client_to_server_ports | map('split', '/') | list) }}"
  loop_control:
    loop_var: rule
  name: Allow Nomad client to server ports
  vars:
    ip: "{{ rule[0] }}"
    port_no: "{{ rule[1] }}"
    proto: "{{ rule[2] }}"
  when: "'manager' in group_names"

- ansible.builtin.set_fact:
    manager_ips: >-
      {{
        groups['manager']
        | map('extract', hostvars, 'ansible_default_ipv4')
        | map(attribute='address')
        | reject('equalto', ansible_default_ipv4.address)
        | list
      }}
  name: Collect other manager IPs

- community.general.ufw:
    from_ip: "{{ ip }}"
    log: true
    proto: "{{ proto }}"
    rule: allow
    to_port: "{{ port_no }}"
  loop: "{{ query('nested', manager_ips, nomad_server_to_server_ports | map('split', '/') | list) }}"
  loop_control:
    loop_var: rule
  name: Allow Nomad server to server ports
  vars:
    ip: "{{ rule[0] }}"
    port_no: "{{ rule[1] }}"
    proto: "{{ rule[2] }}"
  when: "'manager' in group_names"

- community.general.ufw:
    from_ip: 0.0.0.0/0
    log: true
    proto: "{{ proto }}"
    rule: allow
    to_port: "{{ port_no }}"
  loop: "{{ ingress_worker_ports | map('split', '/') }}"
  loop_control:
    loop_var: rule
  name: Allow ingress worker ports
  vars:
    port_no: "{{ rule[0] }}"
    proto: "{{ rule[1] }}"
  when: "'ingress_worker' in group_names"

- ansible.builtin.get_url:
    dest: /etc/apt/keyrings/hashicorp.asc
    force: true
    url: https://apt.releases.hashicorp.com/gpg
  name: Add Hashicorp GPG apt key to the store

- ansible.builtin.command:
    cmd: dpkg --print-architecture
  changed_when: false
  name: Gather Debian package architecture
  register: dpkg_arch

- ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ dpkg_arch.stdout }} signed-by=/etc/apt/keyrings/hashicorp.asc]
      https://apt.releases.hashicorp.com {{ ansible_facts.lsb.codename }} main
  name: Configure Hashicorp APT repository

- ansible.builtin.apt:
    autoclean: true
    autoremove: true
    clean: true
    install_recommends: true
    name: 
      - nomad
      - python3-pip
    state: latest
    update_cache: true
  name: Install Nomad dependencies packages

- ansible.builtin.pip:
    break_system_packages: true
    executable: pip3
    name: python-nomad
  name: Install Nomad Python dependencies packages

- ansible.builtin.slurp:
    src: /home/ansible/.bashrc
  name: Read remote .bashrc into a variable
  register: bashrc_file

- ansible.builtin.set_fact:
    nomad_completion_present: >
      {{ 
        ('complete -C /usr/bin/nomad nomad')
        in (bashrc_file.content | b64decode)
      }}
  name: Check for existing Nomad autocomplete line in .bashrc

- ansible.builtin.command:
    cmd: nomad -autocomplete-install
  become: false
  changed_when: false
  name: Add Nomad autocomplete configuration
  when: not nomad_completion_present

- ansible.builtin.template:
    dest: /etc/nomad.d/nomad.hcl
    group: "{{ 'root' if 'manager' in group_names else 'nomad' }}"
    lstrip_blocks: true
    mode: '0644'
    owner: "{{ 'root' if 'manager' in group_names else 'nomad' }}"
    src: nomad.hcl.j2
    trim_blocks: true
  name: Configure Nomad
  register: nomad_config

- ansible.builtin.template:
    dest: /lib/systemd/system/nomad.service
    group: root
    lstrip_blocks: true
    mode: '0644'
    owner: root
    src: nomad.service.j2
    trim_blocks: true
  name: Configure Nomad service
  register: nomad_service

- ansible.builtin.service:
    enabled: true
    name: nomad
    state: started
  name: Start nomad

- ansible.builtin.service:
    name: nomad
    state: restarted
  name: Restart nomad if configuration or service has been changed
  when:
    - nomad_config.changed or nomad_service.changed

# - community.docker.docker_swarm:
#     validate_certs: true
#   name: Initialize Swarm if needed
#   register: swarm_init
#   when: inventory_hostname == groups['manager'][0]

# - community.docker.docker_swarm_info:
#     validate_certs: true
#   name: Gather Swarm join tokens
#   register: swarm_info
#   when: inventory_hostname == groups['manager'][0]

# - ansible.builtin.set_fact:
#     manager_join_token: "{{ swarm_info.swarm_facts.JoinTokens.Manager }}"
#     worker_join_token: "{{ swarm_info.swarm_facts.JoinTokens.Worker }}"
#   name: Distribute Swarm join tokens
#   when: inventory_hostname == groups['manager'][0]

# - community.docker.docker_swarm:
#     join_token: "{{ hostvars[groups['manager'][0]]['manager_join_token'] }}"
#     remote_addrs:
#       - "{{ hostvars[groups['manager'][0]].ansible_default_ipv4.address }}"
#     state: join
#     validate_certs: true
#   name: Join Docker Swarm as manager node
#   when:
#     - "'manager' in group_names"
#     - inventory_hostname != groups['manager'][0]

# - community.docker.docker_swarm:
#     join_token: "{{ hostvars[groups['manager'][0]]['worker_join_token'] }}"
#     remote_addrs:
#       - "{{ hostvars[groups['manager'][0]].ansible_default_ipv4.address }}"
#     state: join
#     validate_certs: true
#   name: Join Docker Swarm as ingress worker node
#   when:
#     - "'ingress_worker' in group_names"

# - community.docker.docker_swarm:
#     join_token: "{{ hostvars[groups['manager'][0]]['worker_join_token'] }}"
#     remote_addrs:
#       - "{{ hostvars[groups['manager'][0]].ansible_default_ipv4.address }}"
#     state: join
#     validate_certs: true
#   name: Join Docker Swarm as main worker node
#   when:
#     - "'main_worker' in group_names"

# - community.docker.docker_node:
#     hostname: "{{ node }}"
#     labels:
#       eu.cloudskeleton.node: "true"
#       eu.cloudskeleton.node.type: "{{ hostvars[node].group_names[0] | replace('_','-') }}"
#     labels_state: replace
#     validate_certs: true
#   loop: "{{ groups['all'] }}"
#   loop_control:
#     loop_var: node
#   name: Label each node
#   when: inventory_hostname == groups['manager'][0]
...
