---
- ansible.builtin.template:
    dest: /etc/nomad.d/telemetry.hcl
    group: "{{ 'nomad' if 'manager' in group_names else 'root' }}"
    lstrip_blocks: true
    mode: '0640'
    owner: "{{ 'nomad' if 'manager' in group_names else 'root' }}"
    src: telemetry.hcl.j2
    trim_blocks: true
  name: Configure Nomad telemetry
  register: nomad_telemetry_config

- ansible.builtin.command:
    cmd: nomad config validate /etc/nomad.d
  name: Validate Nomad configuration
  when: nomad_telemetry_config.changed

- ansible.builtin.systemd_service:
    daemon_reload: true
    name: nomad
    state: restarted
  name: Restart Nomad if configuration has been changed
  when: nomad_telemetry_config.changed

- ansible.builtin.set_fact:
    main_worker_ips: >-
      {{
        groups['main_worker']
        | map('extract', hostvars, 'ansible_default_ipv4')
        | map(attribute='address')
        | flatten
      }}
  name: Set main worker IP list
  when: "'ingress_worker' in group_names"

- community.general.ufw:
    from_ip: "{{ ip }}"
    log: true
    proto: tcp
    rule: allow
    to_port: 4646
  loop: "{{ main_worker_ips }}"
  loop_control:
    loop_var: ip
  name: Allow Nomad main worker to ingress worker HTTP port (for Prometheus endpoint scraping)
  when: "'ingress_worker' in group_names"

- community.general.ufw:
    from_ip: "{{ nomad_cluster_bridge_network_cidr }}"
    log: true
    proto: tcp
    rule: allow
    to_port: 4646
  name: Allow Nomad local bridge network to HTTP port (for Prometheus endpoint scraping)
  when: "'main_worker' in group_names"
...