---
- ansible.builtin.apt:
    autoclean: true
    autoremove: true
    clean: true
    install_recommends: true
    name:
      - open-iscsi
      - scsitools
    state: latest
    update_cache: true
  name: Ensure CSI dependencies are installed
  when: "'main_worker' in group_names"

- ansible.builtin.template:
    dest: /tmp/csi.nomad
    group: nomad
    lstrip_blocks: true
    mode: '0640'
    owner: nomad
    src: csi.nomad.j2
    trim_blocks: true
  name: Render Nomad CSI node job file
  vars:
    csi_config: "{{ lookup('file', playbook_dir + '/../.csi.yml') }}"
  when: inventory_hostname == groups['manager'][0]

- ansible.builtin.command:
    cmd: nomad job run /tmp/csi.nomad
  environment:
    NOMAD_ADDR: https://localhost:4646
    NOMAD_CACERT: /etc/nomad.d/certs/nomad-agent-ca.pem
    NOMAD_CLIENT_CERT: /etc/nomad.d/certs/global-cli-nomad.pem
    NOMAD_CLIENT_KEY: /etc/nomad.d/certs/global-cli-nomad-key.pem
    NOMAD_TOKEN: "{{ nomad_server_token }}"
  name: Deploy Nomad CSI node job
  when:
    - inventory_hostname == groups['manager'][0]

- ansible.builtin.file:
    path: /tmp/csi.nomad
    state: absent
  name: Remove Nomad CSI node job file
  when: inventory_hostname == groups['manager'][0]

- ansible.builtin.template:
    dest: /tmp/volume.nomad
    group: nomad
    lstrip_blocks: true
    mode: '0640'
    owner: nomad
    src: volume.nomad.j2
    trim_blocks: true
  name: Render Nomad CSI volume definition file
  when: inventory_hostname == groups['manager'][0]

- ansible.builtin.command:
    cmd: nomad volume create /tmp/volume.nomad
  environment:
    NOMAD_ADDR: https://localhost:4646
    NOMAD_CACERT: /etc/nomad.d/certs/nomad-agent-ca.pem
    NOMAD_CLIENT_CERT: /etc/nomad.d/certs/global-cli-nomad.pem
    NOMAD_CLIENT_KEY: /etc/nomad.d/certs/global-cli-nomad-key.pem
    NOMAD_TOKEN: "{{ nomad_server_token }}"
  name: Create or update Nomad CSI volume
  when: inventory_hostname == groups['manager'][0]

- ansible.builtin.file:
    path: /tmp/volume.nomad
    state: absent
  name: Remove Nomad CSI volume definition file
  when: inventory_hostname == groups['manager'][0]
...
