---
- ansible.builtin.copy:
    dest: /etc/democratic-csi.yml
    src: "{{ playbook_dir }}/../.csi.yml"
  name: Copy CSI configuration

- community.docker.docker_plugin:
    alias: democratic-csi-swarm
    plugin_name: ghcr.io/cloud-skeleton/democratic-csi-swarm
    state: enable
    validate_certs: true
  name: Install Democratic CSI (Swarm version) plugin
...
