---
- ansible.builtin.set_fact:
    all_manager_ips: >-
      {{
        groups['manager']
        | map('extract', hostvars, 'ansible_default_ipv4')
        | map(attribute='address') | flatten
      }}
  name: Set all managers IP list
  register: all_manager_ips_fact

- ansible.builtin.set_fact:
    all_worker_ips: >-
      {{
        (groups['main_worker'] + groups['ingress_worker'])
        | map('extract', hostvars, 'ansible_default_ipv4')
        | map(attribute='address') | flatten
      }}
  name: Set all workers IP list
  register: all_worker_ips_fact

- ansible.builtin.set_fact:
    worker_ips: >-
      {{
        ansible_play_hosts
        | reject('in', groups['manager'])
        | map('extract', hostvars, 'ansible_default_ipv4')
        | map(attribute='address')
        | reject('equalto', ansible_default_ipv4.address)
        | list
      }}
  name: Collect other worker IPs

- community.general.ufw:
    from_ip: "{{ ip }}"
    log: true
    proto: "{{ proto }}"
    rule: allow
    to_port: "{{ port_no }}"
  loop: "{{ query('nested', worker_ips, consul_client_to_client_ports | map('split', '/') | list) }}"
  loop_control:
    loop_var: rule
  name: Allow Consul client to client ports
  vars:
    ip: "{{ rule[0] }}"
    port_no: "{{ rule[1] }}"
    proto: "{{ rule[2] }}"
  when: "'manager' not in group_names"

- community.general.ufw:
    from_ip: "{{ ip }}"
    log: true
    proto: "{{ proto }}"
    rule: allow
    to_port: "{{ port_no }}"
  loop: "{{ query('nested', worker_ips, consul_client_to_server_ports | map('split', '/') | list) }}"
  loop_control:
    loop_var: rule
  name: Allow Consul client to server ports
  vars:
    ip: "{{ rule[0] }}"
    port_no: "{{ rule[1] }}"
    proto: "{{ rule[2] }}"
  when: "'manager' in group_names"

- ansible.builtin.set_fact:
    manager_ips: >-
      {{
        groups['manager']
        | map('extract', hostvars, 'ansible_default_ipv4')
        | map(attribute='address')
        | reject('equalto', ansible_default_ipv4.address)
        | list
      }}
  name: Collect other manager IPs

- community.general.ufw:
    from_ip: "{{ ip }}"
    log: true
    proto: "{{ proto }}"
    rule: allow
    to_port: "{{ port_no }}"
  loop: "{{ query('nested', manager_ips, consul_server_to_server_ports | map('split', '/') | list) }}"
  loop_control:
    loop_var: rule
  name: Allow Consul server to server ports
  vars:
    ip: "{{ rule[0] }}"
    port_no: "{{ rule[1] }}"
    proto: "{{ rule[2] }}"
  when: "'manager' in group_names"

- community.general.ufw:
    from_ip: "{{ ip }}"
    log: true
    proto: "{{ proto }}"
    rule: allow
    to_port: "{{ port_no }}"
  loop: "{{ query('nested', nomad_server_http_allow_ip_cidrs, consul_server_admin_ports | map('split', '/') | list) }}"
  loop_control:
    loop_var: rule
  name: Allow admin access to Consul server HTTP endpoints
  vars:
    ip: "{{ rule[0] }}"
    port_no: "{{ rule[1] }}"
    proto: "{{ rule[2] }}"
  when: "'manager' in group_names"

- ansible.builtin.apt:
    autoclean: true
    autoremove: true
    clean: true
    install_recommends: true
    name: consul
    state: latest
    update_cache: true
  name: Install Consul dependencies packages

- ansible.builtin.slurp:
    src: /home/ansible/.bashrc
  name: Read remote .bashrc into a variable
  register: bashrc_file

- ansible.builtin.set_fact:
    consul_completion_present: >
      {{ 
        ('complete -C /usr/bin/consul consul')
        in (bashrc_file.content | b64decode)
      }}
  name: Check for existing Consul autocomplete line in .bashrc

- ansible.builtin.command:
    cmd: consul -autocomplete-install
  become: false
  changed_when: false
  name: Add Consul autocomplete configuration
  when: not consul_completion_present

- ansible.builtin.command:
    cmd: consul keygen
  name: Generate 32 byte random string for encryption
  register: encryption_string
  when:
    - inventory_hostname == groups['manager'][0]
    - consul_encryption_string is not defined

- ansible.builtin.set_fact:
    cacheable: true
    consul_encryption_string: "{{ encryption_string.stdout }}"
  name: Cache the new 32 byte encryption string indefinitely
  when:
    - inventory_hostname == groups['manager'][0]
    - encryption_string.changed

# - import_tasks: certificates.yml

- ansible.builtin.template:
    dest: /etc/consul.d/consul.hcl
    group: consul
    lstrip_blocks: true
    mode: '0640'
    owner: consul
    src: consul.hcl.j2
    trim_blocks: true
  name: Configure Consul
  register: consul_config

- ansible.builtin.command:
    cmd: consul validate /etc/consul.d
  name: Validate Consul configuration
  when: consul_config.changed

- ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    name: consul
    state: started
  name: Start first Consul manager
  when: inventory_hostname == groups['manager'][0]

- ansible.builtin.systemd_service:
    daemon_reload: true
    name: consul
    state: restarted
  name: Restart Consul if configuration or service has been changed
  when:
    - inventory_hostname == groups['manager'][0]
    - >
      consul_config.changed
    # or certificates_updated

- community.general.consul_acl_bootstrap:
    # ca_path: "{{ certificate_files.ca_certificate }}"
    # scheme: https
    state: present
  name: Create Consul ACL boostrap token
  register: bootstrap_token
  when:
    - inventory_hostname == groups['manager'][0]
    - consul_bootstrap_token is not defined

- ansible.builtin.set_fact:
    cacheable: true
    consul_bootstrap_token: "{{ bootstrap_token.result.SecretID }}"
  name: Cache the new bootstrap token indefinitely
  when:
    - inventory_hostname == groups['manager'][0]
    - bootstrap_token.changed
...
