---
  - ansible.builtin.fetch:
      dest: "{{ certificate.path_local }}"
      flat: true
      src: "{{ certificate.path }}"
    name: Copy certificate file to the cache
    when: source

  - ansible.builtin.fetch:
      dest: "{{ private_key.path_local }}"
      flat: true
      src: "{{ private_key.path }}"
    name: Copy private key file to the cache
    when: source

  - ansible.builtin.copy:
      dest: "{{ certificate.path }}"
      src: "{{ certificate.path_local }}"
    name: Distribute certificate file from the cache
    when: certificate.destinations

  - ansible.builtin.file:
      group: consul
      mode: '0750'
      owner: consul
      path: "{{ certificate.path }}"
    name: Set certificate file properties
    when: certificate.destinations

  - ansible.builtin.copy:
      dest: "{{ private_key.path }}"
      src: "{{ private_key.path_local }}"
    name: Distribute private key file from the cache
    when: private_key.destinations

  - ansible.builtin.file:
      group: consul
      mode: '0750'
      owner: consul
      path: "{{ private_key.path }}"
    name: Set private key file properties
    when: private_key.destinations
...
