---
- become: true
  hosts: all
  name: Initialize Docker Swarm Cluster and all prerequisites
  roles:
    - disable_pam_systemd
    - configure_dns
    - set_hostname
    - upgrade_system
    - setup_firewall
    - setup_docker
    - setup_swarm_cluster
...
