---
- become: true
  hosts: all
  name: Initialize Nomad cluster and all prerequisites
  roles:
    # - disable_pam_systemd
    # - configure_dns
    # - set_hostname
    # - upgrade_system
    # - setup_firewall
    # - setup_docker
    - setup_nomad_cluster
    # - setup_volume
...
