---
- become: true
  hosts: all
  name: Initialize Docker Swarm Cluster and all prerequisites
  roles:
    - disable_pam_systemd
    - configure_dns
    - system_upgrade
    - setup_firewall
    - setup_docker
...
