---
certificate_files:
  ca_certificate: "/etc/nomad.d/certs/{{ certificate.domain_name }}-agent-ca.pem"
  ca_private_key: "/etc/nomad.d/certs/{{ certificate.domain_name }}-agent-ca-key.pem"
  local_ca_certificate: "{{ playbook_dir }}/../.cache/{{ certificate.domain_name }}-agent-ca.pem"
  local_ca_private_key: "{{ playbook_dir }}/../.cache/{{ certificate.domain_name }}-agent-ca-key.pem"

first_manager: "{{ groups['manager'][0] }}"

ingress_worker_ports:
  - 80/tcp
  - 443/tcp
  - 443/udp

nomad_client_drain_max_time: 10m

nomad_client_to_server_ports:
  - 4646/tcp
  - 4647/tcp

nomad_server_admin_ports:
  - 4646/tcp

nomad_server_to_server_ports:
  - 4647/tcp
  - 4648/tcp
  - 4648/udp
...
