---
certificate_files:
  ca_certificate: "/etc/nomad.d/certs/{{ certificate.domain_name }}-agent-ca.pem"
  ca_certificate_local: "{{ playbook_dir }}/../.cache/{{ certificate.domain_name }}-agent-ca.pem"
  ca_private_key: "/etc/nomad.d/certs/{{ certificate.domain_name }}-agent-ca-key.pem"
  ca_private_key_local: "{{ playbook_dir }}/../.cache/{{ certificate.domain_name }}-agent-ca-key.pem"
  client_certificate: "/etc/nomad.d/certs/global-client-{{ certificate.domain_name }}.pem"
  client_certificate_local: "{{ playbook_dir }}/../.cache/global-client-{{ certificate.domain_name }}.pem"
  client_private_key: "/etc/nomad.d/certs/global-client-{{ certificate.domain_name }}-key.pem"
  client_private_key_local: "{{ playbook_dir }}/../.cache/global-client-{{ certificate.domain_name }}-key.pem"
  server_certificate: "/etc/nomad.d/certs/global-server-{{ certificate.domain_name }}.pem"
  server_certificate_local: "{{ playbook_dir }}/../.cache/global-server-{{ certificate.domain_name }}.pem"
  server_private_key: "/etc/nomad.d/certs/global-server-{{ certificate.domain_name }}-key.pem"
  server_private_key_local: "{{ playbook_dir }}/../.cache/global-server-{{ certificate.domain_name }}-key.pem"

first_manager: "{{ groups['manager'][0] }}"

ingress_worker_ports:
  - 80/tcp
  - 443/tcp
  - 443/udp

nomad_client_drain_max_time: 10m

nomad_client_to_server_ports:
  - 4646/tcp
  - 4647/tcp

nomad_server_admin_ports:
  - 4646/tcp

nomad_server_to_server_ports:
  - 4647/tcp
  - 4648/tcp
  - 4648/udp
...
